version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install Prerequests"
          command: "sudo apt-get update && sudo apt-get install -y build-essential sdcc=4.0.0"
      - run:
          name: "Build and Test VGS-Zero"
          command: "make tests"

workflows:
  test-workflow:
    jobs:
      - test
